spring:
  datasource:
    url: jdbc:mysql://database-2.claqadurzooy.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: jtyu0807
  jpa:
    hibernate:
      ddl-auto: none # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true

jwt:
  key: dq2k1@((1e9101k-d01k-132019dj9j29@)@@@201kd1-01-0dmwoidnwdbwdbawdiawnd26816
  access-token-expiration-minutes: 8000
  refresh-token-expiration-minutes: 8000